# Generated by Django 5.1.15 on 2026-07-08 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('importer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source_import_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='importer.importrow'),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.group'),
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='expenses.group'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_windows', to='expenses.member'),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='expenses.member'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='expenses.member'),
        ),
        migrations.AddField(
            model_name='memberalias',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='expenses.member'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='from_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to='expenses.member'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='expenses.group'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='source_import_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to='importer.importrow'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='to_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to='expenses.member'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('group', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='expensesplit',
            unique_together={('expense', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='memberalias',
            unique_together={('member', 'normalized')},
        ),
    ]
