# Generated by Django 5.1.15 on 2026-07-08 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('committed', 'Committed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='expenses.group')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw', models.JSONField()),
                ('cleaned', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('settlement', 'Settlement'), ('duplicate', 'Duplicate (drop)'), ('invalid', 'Invalid (drop)')], default='expense', max_length=16)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('skipped', 'Skipped'), ('committed', 'Committed')], default='clean', max_length=16)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('resolution', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importer.importbatch')),
            ],
            options={
                'ordering': ['batch_id', 'row_number'],
                'unique_together': {('batch', 'row_number')},
            },
        ),
    ]
