# Generated by Django 5.1.15 on 2026-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField()),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(default='frankfurter', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('on_date', 'base', 'quote')},
            },
        ),
    ]
